import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav / Header
    "nav.concept": "Concept",
    "nav.register": "Registration",
    "nav.registry": "Live Registry",
    "nav.verify": "Verification",
    "app.title": "Asli Taana",
    
    // Footer
    "footer.title": "Asli Taana — National Handloom Hackathon 2026",
    "footer.subtitle": "Preserving cultural heritage and protecting weaver economics using AI thread fingerprinting.",
    "footer.built": "Built with Love",
    "footer.respect": "& respect for Indian Weavers",

    // Concept Section
    "concept.badge": "National Handloom Hackathon",
    "concept.title1": "Securing",
    "concept.title2": "The Real Thread",
    "concept.title3": "of India",
    "concept.desc": "Asli Taana uses AI-driven textile fingerprinting to authenticate genuine handloom fabrics, protecting artisan livelihoods from powerloom counterfeits.",
    
    "concept.problem.title": "The Powerloom Threat",
    "concept.problem.desc": "In famous villages like Kuthampully, over 100 shops claim to sell authentic handloom sarees. In reality, only one cooperative still weaves by hand. The rest are cheap powerloom copies.",
    "concept.problem.point1.title": "Replication Speed:",
    "concept.problem.point1.desc": "A machine copies handwoven patterns in minutes; a real weaver spends days, thread by thread.",
    "concept.problem.point2.title": "Price Undercutting:",
    "concept.problem.point2.desc": "Authentic sarees cost ₹12,000+ to compensate skilled labor, but fakes sell for under ₹2,000.",
    "concept.problem.point3.title": "Law Enforcement Gap:",
    "concept.problem.point3.desc": "The 1985 Handloom Act bans powerloom replication, but inspectors cannot visually tell the difference.",

    "concept.solution.title": "The Artisan Value",
    "concept.solution.desc": "A human weaver naturally creates microscopic irregularities—varying thread tension, tiny gaps, and occasional slubs. These micro-irregularities form a uniquely uncopiable cloth fingerprint.",
    "concept.solution.point1.title": "Uncopiable Code:",
    "concept.solution.point1.desc": "If a fake seller duplicates a QR label, the shopper's fresh macro-photo of the weave will still mismatch the registry.",
    "concept.solution.point2.title": "Zero Equipment:",
    "concept.solution.point2.desc": "Cooperative offices register items with a macro-lens. Shoppers authenticate instantly using native smartphone cameras.",
    "concept.solution.point3.title": "Artisan Protection:",
    "concept.solution.point3.desc": "Redirects market capital to actual craftsmen, driving a fair economy and cultural preservation.",
    
    "concept.fingerprint.badge": "Microscopic Magnification Comparison",
    "concept.fingerprint.title": "Comparing Weave Fingerprints",
    "concept.fingerprint.organic": "Organic",
    "concept.fingerprint.handwoven.title": "A. Handwoven Thread \"Fingerprint\"",
    "concept.fingerprint.handwoven.desc": "Tiny random waves and thread variations (slubs) happen naturally. No two spots are identical.",
    "concept.fingerprint.machine": "Machine",
    "concept.fingerprint.machine.title": "B. Powerloom Thread Grid",
    "concept.fingerprint.machine.desc": "Mechanized weaving creates a mathematically perfect, repetitive grid lacking human touch.",

    // Register Form
    "register.badge": "Step 1: Artisan Registration",
    "register.title": "Saree Identity Creation",
    "register.subtitle": "Securely register handwoven garments and generate uncopiable thread fingerprints",
    "register.artisanInfo": "Artisan Information",
    "register.name": "Master Weaver Name",
    "register.headshot": "Headshot Photo",
    "register.upload": "Upload",
    "register.uploaded": "Uploaded",
    "register.age": "Weaver Age",
    "register.bio": "Short Biography",
    "register.village": "Village / Cluster",
    "register.coop": "Cooperative Society",
    "register.garmentInfo": "Garment Information",
    "register.pattern": "Garment / Pattern Name",
    "register.material": "Material Blend",
    "register.labor": "Days of Labor",
    "register.price": "Fair Trade Value (₹)",
    "register.color": "Garment Color Palette",
    "register.color.placeholder": "Enter color (e.g. red) or #hex",
    "register.color.add": "Add",
    "register.color.traditional": "Traditional Indian Themes:",
    "register.color.kanchi": "Kanchipuram (Mustard & Maroon)",
    "register.color.bandhani": "Bandhani (Black & Red)",
    "register.color.kasavu": "Kasavu (White & Gold)",
    "register.color.phulkari": "Phulkari (Yellow & Crimson)",
    
    "register.submit": "Register Saree & Generate Certificate",
    "register.uploading": "Uploading structural fingerprint...",
    "register.fingerprint": "MASTER FINGERPRINT CAPTURE (MANDATORY)",
    "register.camera": "Use Camera",
    "register.uploadBtn": "Upload Photo",
    "register.retake": "Retake",
    "register.ready": "Fingerprint Ready",
    "register.missing": "Missing Master Fingerprint",
    "register.mismatch.title": "AI Consistency Warning",
    "register.mismatch.desc": "The AI detected a style that may not match your entry. Double check before generating the certificate.",
    "register.mismatch.detected": "Detected Style:",
    "register.mismatch.confidence": "Confidence Level:",
    "register.success.title": "Registration Successful",
    "register.success.desc": "The saree has been securely added to the digital registry. A certificate of authenticity and QR code have been generated.",
    "register.success.id": "Saree ID:",
    "register.cert.title": "Certificate of Authenticity",
    "register.cert.subtitle": "ASLI TAANA DIGITAL REGISTRY",
    "register.cert.id": "REGISTRATION ID",
    "register.cert.weaver": "MASTER WEAVER",
    "register.cert.origin": "ORIGIN CLUSTER",
    "register.cert.date": "VERIFIED DATE",
    "register.cert.footer": "This document certifies that the above garment has been structurally fingerprinted and registered as authentic handloom.",
    "register.cert.download": "Download Certificate",
    "register.qr.download": "Download QR",
    "register.form.reset": "Register Another Garment",
    
    // Registry (SareeList)
    "registry.search": "Search by ID, artisan name, material weave...",
    "registry.filter": "Cluster Filter:",
    "registry.all": "All Clusters",
    "registry.empty": "No registered sarees found matching your query.",
    "registry.weaver": "Weaver",
    "registry.material": "Material",
    "registry.date": "Registered",
    "registry.price": "Artisan Pricing",
    "registry.verify": "Test Verify",
    "registry.ai.detected": "AI DETECTED:",
    "registry.ai.none": "No Style Detected",
    "registry.card.age": "YRS",
    "registry.card.rupee": "₹",
    "registry.card.days": "days labor",
    
    // Verify Section
    "verify.step1": "Step 1: Scan Label or Select ID",
    "verify.title1": "Claimed Saree Identity",
    "verify.active": "Active Saree ID (QR Target)",
    "verify.select.prompt": "Select a Saree to Verify",
    "verify.select.option": "Select a registered saree...",
    
    "verify.step2": "Step 2: Simulate or Capture Retail Store Scan",
    "verify.title2": "Fresh Shop Scan",
    "verify.btn.genuine": "Genuine",
    "verify.btn.genuineDesc": "Authentic registered handwoven saree.",
    "verify.btn.clone": "Powerloom Clone",
    "verify.btn.cloneDesc": "Counterfeit: machine grid lines.",
    "verify.btn.diff": "Different Saree",
    "verify.btn.diffDesc": "Scan of a completely different weaver.",
    "verify.orig": "Registered Original",
    "verify.retail": "Retail Shop Photo",
    "verify.run": "Run AI Authenticity Engine",
    "verify.analyzing": "Analyzing Structural Fingerprint...",
    "verify.style": "AI-Identified Weaving Style",
    "verify.style.disclaimer": "This identifies visual styling motifs and not literal geographic origin.",
    "verify.active": "Active Saree ID (QR Target)",
    "verify.active.placeholder": "Select Saree or Scan QR",
    "verify.claimedPattern": "Claimed Pattern Type",
    "verify.fairTrade": "Fair Trade Value",
    "verify.registeredArtisan": "Registered Master Artisan",
    "verify.villageCluster": "Village Cluster",
    "verify.labor": "Artisan Labor",
    "verify.palette": "Garment Palette",
    "concept.problem.title": "The Powerloom Threat",
    "concept.problem.desc": "Machine-made imitations are flooding the market, deceiving consumers and destroying traditional livelihoods.",
    "concept.problem.point1.title": "Artisan Wage Theft:",
    "concept.problem.point1.desc": "Weavers lose up to 70% of their income to powerloom counterfeits.",
    "concept.problem.point2.title": "Heritage Erosion:",
    "concept.problem.point2.desc": "Ancient, complex motifs are cheaply mass-printed, degrading the art form.",
    "concept.problem.point3.title": "Consumer Deception:",
    "concept.problem.point3.desc": "Buyers pay premium prices for synthetic fakes disguised as handlooms.",
    "concept.solution.title": "The Artisan Value",
    "concept.solution.desc": "Authentic handlooms are woven with soul, bearing microscopic signatures of human craftsmanship that no machine can replicate.",
    "concept.solution.point1.title": "Fair Compensation:",
    "concept.solution.point1.desc": "Authentication ensures 100% of the premium value goes to the creator.",
    "concept.solution.point2.title": "Cultural Preservation:",
    "concept.solution.point2.desc": "Sustains ancient weaving techniques and regional biodiversity.",
    "concept.solution.point3.title": "Verified Authenticity:",
    "concept.solution.point3.desc": "Immutable proof of origin, labor, and material purity.",
    "register.headshot": "Headshot Photo",
    "register.uploaded": "Uploaded",
    "register.upload": "Upload Photo",
    "register.capture": "Capture Macro",
    "register.cameraRequired": "Camera capture or macro photo upload required",
    "register.awaiting": "Awaiting Registration",
    "register.awaitingDesc": "Fill out the artisan form, capture the master fingerprint, and click \"Register Saree\" to compile your structural fingerprint and print certificates.",
    "saree.name": "Weaver Name",
    "saree.area": "Area / Village",
    "saree.date": "Date",
    "saree.organization": "Organization",
    "default.weaverName": "Rajendra Prasad",
    "default.village": "Chanderi",
    "default.cooperative": "Chanderi Handloom Weavers Union",
    "default.pattern": "Chanderi Golden Booti Saree",
    "default.material": "Silk",
    "Chanderi": "Chanderi",
    "Kuthampully": "Kuthampully",
    "Kanchipuram": "Kanchipuram",
    "Paithan": "Paithan",
    "Chanderi Golden Booti Saree": "Chanderi Golden Booti Saree",
    "Traditional Kasavu Saree": "Traditional Kasavu Saree",
    "Temple Border Silk Saree": "Temple Border Silk Saree",
    "Paithani Traditional Peacock Saree": "Paithani Traditional Peacock Saree",
    "Rajendra Prasad": "Rajendra Prasad",
    "Lakshmi Devi": "Lakshmi Devi",
    "Ramanathan K.": "Ramanathan K.",
    "Savita Patwardhan": "Savita Patwardhan",
    "Chanderi Handloom Weavers Union": "Chanderi Handloom Weavers Union",
    "Kuthampully Handloom Weavers Cooperative Society": "Kuthampully Handloom Weavers Cooperative Society",
    "Kanchipuram Silk-Weavers Cooperative Society Ltd.": "Kanchipuram Silk-Weavers Cooperative Society Ltd.",
    "Maharashtra State Handlooms Development Corporation": "Maharashtra State Handlooms Development Corporation",
    "Silk": "Silk",
    "Traditional Kasavu Cotton (Fine 100s count) with Pure Silver-Gilt Zari": "Traditional Kasavu Cotton (Fine 100s count) with Pure Silver-Gilt Zari",
    "100% Pure Mulberry Silk (Double Warp) with 22k Gold Threading": "100% Pure Mulberry Silk (Double Warp) with 22k Gold Threading",
    "Fine Mulberry Silk with Pure Zari Border and Peacock Pallu": "Fine Mulberry Silk with Pure Zari Border and Peacock Pallu",
    "verify.conf": "Confidence Level:",
    "verify.result.match": "AUTHENTIC HANDLOOM MATCH",
    "verify.result.mismatch": "COUNTERFEIT / MISMATCH DETECTED",
    "verify.result.score": "Confidence Score:",
    "verify.result.reason": "AI Analysis:",
    
    // WhatsApp Bot Simulator
    "register.tab.web": "Web Form",
    "register.tab.whatsapp": "WhatsApp Bot",
    "whatsapp.header.name": "Asli Taana Bot",
    "whatsapp.header.status": "online",
    "whatsapp.bot.msg1": "Welcome to Asli Taana! What is your full name?",
    "whatsapp.bot.msg2": "Great! Which village or cluster are you from?",
    "whatsapp.bot.msg3": "Which cooperative society are you associated with?",
    "whatsapp.bot.msg4": "What pattern or saree type are you registering?",
    "whatsapp.bot.msg5": "What material is it made of?",
    "whatsapp.bot.msg6": "What is your fair trade price for this piece (in ₹)?",
    "whatsapp.bot.msg7": "Finally, please take a clear macro photo (close-up) of the weave for the fingerprint registry.",
    "whatsapp.bot.msg8": "Thank you! Your saree has been successfully registered. The certificate will be available in the Live Registry.",
    "whatsapp.user.reply.photo": "Sent photo 📷",
    "whatsapp.btn.send": "Send",
    "whatsapp.placeholder": "Type a message...",

    // Loading
    "loading.subtitle": "The Real Thread",
  },
  hi: {
    // Nav / Header
    "nav.concept": "अवधारणा",
    "nav.register": "पंजीकरण",
    "nav.registry": "लाइव रजिस्ट्री",
    "nav.verify": "सत्यापन",
    "app.title": "असली ताना",
    
    // Footer
    "footer.title": "असली ताना — राष्ट्रीय हथकरघा हैकथॉन 2026",
    "footer.subtitle": "एआई फिंगरप्रिंटिंग का उपयोग करके सांस्कृतिक विरासत और बुनकरों की अर्थव्यवस्था की रक्षा करना।",
    "footer.built": "प्यार से बनाया गया",
    "footer.respect": "और भारतीय बुनकरों के लिए सम्मान",

    // Concept Section
    "concept.badge": "राष्ट्रीय हथकरघा हैकथॉन",
    "concept.title1": "सुरक्षित करना",
    "concept.title2": "असली धागा",
    "concept.title3": "भारत का",
    "concept.desc": "असली ताना पावरलूम जालसाजी से कारीगरों की आजीविका की रक्षा करते हुए, वास्तविक हथकरघा कपड़ों को प्रमाणित करने के लिए एआई टेक्सटाइल फिंगरप्रिंटिंग का उपयोग करता है।",
    
    "concept.problem.title": "पावरलूम का खतरा",
    "concept.problem.desc": "कुथम्पुल्ली जैसे प्रसिद्ध गांवों में, 100 से अधिक दुकानें प्रामाणिक हथकरघा साड़ियां बेचने का दावा करती हैं। वास्तव में, केवल एक सहकारी समिति अभी भी हाथ से बुनती है। बाकी सस्ते पावरलूम की प्रतियां हैं।",
    "concept.problem.point1.title": "प्रतिकृति की गति:",
    "concept.problem.point1.desc": "एक मशीन मिनटों में हाथ से बुने हुए पैटर्न की नकल करती है; एक असली बुनकर धागे दर धागे दिन बिताता है।",
    "concept.problem.point2.title": "मूल्य में कटौती:",
    "concept.problem.point2.desc": "कुशल श्रम की भरपाई के लिए प्रामाणिक साड़ियों की कीमत ₹12,000+ है, लेकिन नकली ₹2,000 से कम में बिकती हैं।",
    "concept.problem.point3.title": "कानून प्रवर्तन अंतर:",
    "concept.problem.point3.desc": "1985 का हथकरघा अधिनियम पावरलूम प्रतिकृति पर प्रतिबंध लगाता है, लेकिन निरीक्षक नेत्रहीन अंतर नहीं बता सकते हैं।",

    "concept.solution.title": "कारीगर का मूल्य",
    "concept.solution.desc": "एक मानव बुनकर स्वाभाविक रूप से सूक्ष्म अनियमितताएं पैदा करता है - अलग-अलग धागे का तनाव, छोटे अंतराल और कभी-कभी स्लब। ये सूक्ष्म-अनियमितताएं एक विशिष्ट रूप से अजेय कपड़े का फिंगरप्रिंट बनाती हैं।",
    "concept.solution.point1.title": "अजेय कोड:",
    "concept.solution.point1.desc": "यदि कोई नकली विक्रेता क्यूआर लेबल की नकल करता है, तो भी खरीदार की बुनाई की ताजा मैक्रो-फोटो रजिस्ट्री से मेल नहीं खाएगी।",
    "concept.solution.point2.title": "शून्य उपकरण:",
    "concept.solution.point2.desc": "सहकारी समितियाँ मैक्रो-लेंस वाले आइटम पंजीकृत करती हैं। खरीदार स्मार्टफोन कैमरे का उपयोग करके तुरंत प्रमाणित करते हैं।",
    "concept.solution.point3.title": "कारीगर संरक्षण:",
    "concept.solution.point3.desc": "बाजार पूंजी को वास्तविक शिल्पकारों की ओर पुनर्निर्देशित करता है, जिससे एक निष्पक्ष अर्थव्यवस्था और सांस्कृतिक संरक्षण को बढ़ावा मिलता है।",

    "concept.fingerprint.badge": "सूक्ष्म आवर्धन तुलना",
    "concept.fingerprint.title": "बुनाई फिंगरप्रिंट की तुलना",
    "concept.fingerprint.organic": "जैविक (हाथ की बुनाई)",
    "concept.fingerprint.handwoven.title": "A. हाथ से बुना हुआ धागा \"फिंगरप्रिंट\"",
    "concept.fingerprint.handwoven.desc": "छोटी यादृच्छिक लहरें और धागे की विविधताएं (स्लब) स्वाभाविक रूप से होती हैं। कोई भी दो स्थान समान नहीं हैं।",
    "concept.fingerprint.machine": "मशीन",
    "concept.fingerprint.machine.title": "B. पावरलूम धागा ग्रिड",
    "concept.fingerprint.machine.desc": "मशीनीकृत बुनाई एक गणितीय रूप से परिपूर्ण, दोहरावदार ग्रिड बनाती है जिसमें मानवीय स्पर्श का अभाव होता है।",

    // Register Form
    "register.badge": "चरण 1: कारीगर पंजीकरण",
    "register.title": "साड़ी पहचान निर्माण",
    "register.subtitle": "हाथ से बुने हुए कपड़ों को सुरक्षित रूप से पंजीकृत करें और अजेय धागा फिंगरप्रिंट उत्पन्न करें",
    "register.artisanInfo": "कारीगर की जानकारी",
    "register.name": "मास्टर बुनकर का नाम",
    "register.headshot": "हेडशॉट फोटो",
    "register.upload": "अपलोड",
    "register.uploaded": "अपलोड किया गया",
    "register.age": "बुनकर की आयु",
    "register.bio": "संक्षिप्त जीवनी",
    "register.village": "गाँव / क्लस्टर",
    "register.coop": "सहकारी संघ",
    "register.garmentInfo": "कपड़े की जानकारी",
    "register.pattern": "परिधान / पैटर्न का नाम",
    "register.material": "सामग्री मिश्रण",
    "register.labor": "श्रम के दिन",
    "register.price": "उचित व्यापार मूल्य (₹)",
    "register.color": "कपड़े का रंग पैलेट",
    "register.color.placeholder": "रंग (उदा. red) या #hex दर्ज करें",
    "register.color.add": "जोड़ें",
    "register.color.traditional": "पारंपरिक भारतीय थीम:",
    "register.color.kanchi": "कांचीपुरम (सरसों और मैरून)",
    "register.color.bandhani": "बंधनी (काला और लाल)",
    "register.color.kasavu": "कासावु (सफेद और सोना)",
    "register.color.phulkari": "फुलकारी (पीला और लाल)",

    "register.submit": "साड़ी पंजीकृत करें और प्रमाणपत्र उत्पन्न करें",
    "register.uploading": "संरचनात्मक फिंगरप्रिंट अपलोड हो रहा है...",
    "register.fingerprint": "मास्टर फिंगरप्रिंट कैप्चर (अनिवार्य)",
    "register.camera": "कैमरा का प्रयोग करें",
    "register.uploadBtn": "फोटो अपलोड करें",
    "register.retake": "फिर से लें",
    "register.ready": "फिंगरप्रिंट तैयार",
    "register.missing": "मास्टर फिंगरप्रिंट गायब है",
    "register.mismatch.title": "एआई संगति चेतावनी",
    "register.mismatch.desc": "एआई ने एक शैली का पता लगाया है जो आपकी प्रविष्टि से मेल नहीं खा सकती है। प्रमाणपत्र उत्पन्न करने से पहले दोबारा जांच करें।",
    "register.mismatch.detected": "पता लगाई गई शैली:",
    "register.mismatch.confidence": "विश्वास का स्तर:",
    "register.success.title": "पंजीकरण सफल",
    "register.success.desc": "साड़ी को सुरक्षित रूप से डिजिटल रजिस्ट्री में जोड़ दिया गया है। प्रामाणिकता का एक प्रमाण पत्र और क्यूआर कोड उत्पन्न किया गया है।",
    "register.success.id": "साड़ी आईडी:",
    "register.cert.title": "प्रामाणिकता का प्रमाण पत्र",
    "register.cert.subtitle": "असली ताना डिजिटल रजिस्ट्री",
    "register.cert.id": "पंजीकरण आईडी",
    "register.cert.weaver": "मास्टर बुनकर",
    "register.cert.origin": "मूल क्लस्टर",
    "register.cert.date": "सत्यापित तिथि",
    "register.cert.footer": "यह दस्तावेज़ प्रमाणित करता है कि उपरोक्त परिधान को संरचनात्मक रूप से फिंगरप्रिंट किया गया है और प्रामाणिक हथकरघा के रूप में पंजीकृत किया गया है।",
    "register.cert.download": "प्रमाणपत्र डाउनलोड करें",
    "register.qr.download": "क्यूआर डाउनलोड करें",
    "register.form.reset": "एक और परिधान पंजीकृत करें",
    
    // Registry (SareeList)
    "registry.search": "आईडी, कारीगर का नाम, सामग्री द्वारा खोजें...",
    "registry.filter": "क्लस्टर फ़िल्टर:",
    "registry.all": "सभी क्लस्टर",
    "registry.empty": "आपकी खोज से मेल खाने वाली कोई पंजीकृत साड़ी नहीं मिली।",
    "registry.weaver": "बुनकर",
    "registry.material": "सामग्री",
    "registry.date": "पंजीकृत",
    "registry.price": "कारीगर मूल्य निर्धारण",
    "registry.verify": "सत्यापन परीक्षण",
    "registry.ai.detected": "एआई द्वारा पहचाना गया:",
    "registry.ai.none": "कोई शैली नहीं मिली",
    "registry.card.age": "वर्ष",
    "registry.card.rupee": "₹",
    "registry.card.days": "श्रम के दिन",
    
    // Verify Section
    "verify.step1": "चरण 1: लेबल स्कैन करें या आईडी चुनें",
    "verify.title1": "दावा की गई साड़ी की पहचान",
    "verify.active": "सक्रिय साड़ी आईडी (क्यूआर लक्ष्य)",
    "verify.select.prompt": "सत्यापित करने के लिए एक साड़ी का चयन करें",
    "verify.select.option": "एक पंजीकृत साड़ी का चयन करें...",
    
    "verify.step2": "चरण 2: रिटेल स्टोर स्कैन का अनुकरण करें",
    "verify.title2": "ताजा दुकान स्कैन",
    "verify.btn.genuine": "असली",
    "verify.btn.genuineDesc": "प्रामाणिक पंजीकृत हथकरघा साड़ी।",
    "verify.btn.clone": "पावरलूम क्लोन",
    "verify.btn.cloneDesc": "नकली: मशीन ग्रिड लाइनें।",
    "verify.btn.diff": "विभिन्न साड़ी",
    "verify.btn.diffDesc": "एक पूरी तरह से अलग बुनकर का स्कैन।",
    "verify.orig": "पंजीकृत मूल",
    "verify.retail": "रिटेल दुकान की फोटो",
    "verify.run": "एआई प्रामाणिकता इंजन चलाएं",
    "verify.analyzing": "संरचनात्मक फिंगरप्रिंट का विश्लेषण हो रहा है...",
    "verify.style": "एआई-पहचानी गई बुनाई शैली",
    "verify.style.disclaimer": "यह दृश्य स्टाइलिंग रूपांकनों की पहचान करता है, न कि शाब्दिक भौगोलिक मूल की।",
    "verify.active": "सक्रिय साड़ी आईडी (क्यूआर लक्ष्य)",
    "verify.active.placeholder": "साड़ी चुनें या क्यूआर स्कैन करें",
    "verify.claimedPattern": "दावा किया गया पैटर्न प्रकार",
    "verify.fairTrade": "उचित व्यापार मूल्य",
    "verify.registeredArtisan": "पंजीकृत मास्टर कारीगर",
    "verify.villageCluster": "ग्राम क्लस्टर",
    "verify.labor": "कारीगर श्रम",
    "verify.palette": "परिधान पैलेट",

    "default.weaverName": "राजेंद्र प्रसाद",
    "default.village": "चंदेरी",
    "default.cooperative": "चंदेरी हथकरघा बुनकर संघ",
    "default.pattern": "चंदेरी गोल्डन बूटी साड़ी",
    "default.material": "रेशम",

    // WhatsApp Bot Simulator
    "register.tab.web": "वेब फॉर्म",
    "register.tab.whatsapp": "व्हाट्सएप बॉट",
    "whatsapp.header.name": "असली ताना बॉट",
    "whatsapp.header.status": "ऑनलाइन",
    "whatsapp.bot.msg1": "नमस्ते! असली ताना में आपका स्वागत है। आपका पूरा नाम क्या है?",
    "whatsapp.bot.msg2": "बहुत बढ़िया! आप किस गाँव या क्लस्टर से हैं?",
    "whatsapp.bot.msg3": "आप किस सहकारी समिति से जुड़े हैं?",
    "whatsapp.bot.msg4": "आप कौन सा पैटर्न या साड़ी प्रकार पंजीकृत कर रहे हैं?",
    "whatsapp.bot.msg5": "यह किस सामग्री से बना है?",
    "whatsapp.bot.msg6": "इस परिधान के लिए आपका उचित व्यापार मूल्य क्या है (₹ में)?",
    "whatsapp.bot.msg7": "अंत में, कृपया फिंगरप्रिंट रजिस्ट्री के लिए बुनाई का एक स्पष्ट मैक्रो फोटो (नजदीक से) लें।",
    "whatsapp.bot.msg8": "धन्यवाद! आपकी साड़ी सफलतापूर्वक पंजीकृत हो गई है। प्रमाणपत्र लाइव रजिस्ट्री में उपलब्ध होगा।",
    "whatsapp.user.reply.photo": "फोटो भेजा 📷",
    "whatsapp.btn.send": "भेजें",
    "whatsapp.placeholder": "एक संदेश टाइप करें...",

    "Chanderi": "चंदेरी",
    "Kuthampully": "कुथमपुल्ली",
    "Kanchipuram": "कांचीपुरम",
    "Paithan": "पैठण",
    "Chanderi Golden Booti Saree": "चंदेरी गोल्डन बूटी साड़ी",
    "Traditional Kasavu Saree": "पारंपरिक कसावू साड़ी",
    "Temple Border Silk Saree": "मंदिर बॉर्डर रेशम साड़ी",
    "Paithani Traditional Peacock Saree": "पैठानी पारंपरिक मोर साड़ी",
    "Rajendra Prasad": "राजेंद्र प्रसाद",
    "Lakshmi Devi": "लक्ष्मी देवी",
    "Ramanathan K.": "रामानाथन के.",
    "Savita Patwardhan": "सविता पटवर्धन",
    "Chanderi Handloom Weavers Union": "चंदेरी हथकरघा बुनकर संघ",
    "Kuthampully Handloom Weavers Cooperative Society": "कुथमपुल्ली हथकरघा बुनकर सहकारी समिति",
    "Kanchipuram Silk-Weavers Cooperative Society Ltd.": "कांचीपुरम रेशम-बुनकर सहकारी समिति लि.",
    "Maharashtra State Handlooms Development Corporation": "महाराष्ट्र राज्य हथकरघा विकास निगम",
    "Silk": "रेशम",
    "Traditional Kasavu Cotton (Fine 100s count) with Pure Silver-Gilt Zari": "पारंपरिक कसावू कपास (महीन 100s काउंट) शुद्ध सिल्वर-गिल्ट ज़री के साथ",
    "100% Pure Mulberry Silk (Double Warp) with 22k Gold Threading": "100% शुद्ध शहतूत रेशम (डबल वार्प) 22k सोने के धागे के साथ",
    "Fine Mulberry Silk with Pure Zari Border and Peacock Pallu": "शुद्ध ज़री बॉर्डर और मोर पल्लू के साथ महीन शहतूत रेशम",
    "verify.conf": "विश्वास का स्तर:",
    "verify.result.match": "प्रामाणिक हथकरघा मैच",
    "verify.result.mismatch": "नकली / बेमेल का पता चला",
    "verify.result.score": "विश्वास स्कोर:",
    "verify.result.reason": "एआई विश्लेषण:",
    
    // Loading
    "loading.subtitle": "असली धागा",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
